/* eslint-disable */
// AUTO-GENERATED by scripts/generate-curriculum.ts — do not edit by hand.
// Add subject JSON under data/curriculum/<grade>/ then re-run the script.

import grade3Meta from "@/data/curriculum/grade-3/meta.json"
import grade3Geography from "@/data/curriculum/grade-3/geography.json"
import grade3Grade3Computer from "@/data/curriculum/grade-3/grade-3-computer.json"
import grade3Grade3English from "@/data/curriculum/grade-3/grade-3-english.json"
import grade3Grade3Tamil from "@/data/curriculum/grade-3/grade-3-tamil.json"
import grade3Math from "@/data/curriculum/grade-3/math.json"
import grade3Science from "@/data/curriculum/grade-3/science.json"
import grade7Meta from "@/data/curriculum/grade-7/meta.json"
import grade7Geography from "@/data/curriculum/grade-7/geography.json"
import grade7Grade7Computer from "@/data/curriculum/grade-7/grade-7-computer.json"
import grade7Grade7English from "@/data/curriculum/grade-7/grade-7-english.json"
import grade7Grade7Tamil from "@/data/curriculum/grade-7/grade-7-tamil.json"
import grade7Math from "@/data/curriculum/grade-7/math.json"
import grade7Science from "@/data/curriculum/grade-7/science.json"

export const gradeData = [
  {
    ...grade3Meta,
    subjects: [grade3Math, grade3Science, grade3Geography, grade3Grade3English, grade3Grade3Tamil, grade3Grade3Computer],
  },
  {
    ...grade7Meta,
    subjects: [grade7Math, grade7Science, grade7Geography, grade7Grade7English, grade7Grade7Tamil, grade7Grade7Computer],
  },
] as const
