/**
 * Scans data/curriculum/<grade>/ and generates lib/curriculum.generated.ts
 * with static JSON imports the client bundle can use.
 *
 * Drop a subject JSON next to meta.json, then re-run this script (or npm run dev/build).
 */
import fs from "node:fs"
import path from "node:path"

const ROOT = path.resolve(import.meta.dirname, "..")
const CURRICULUM_DIR = path.join(ROOT, "data", "curriculum")
const OUT_FILE = path.join(ROOT, "lib", "curriculum.generated.ts")

interface MetaJson {
  id: string
  title: string
  subjectOrder?: string[]
}

interface SubjectJson {
  id: string
  title: string
}

function toIdent(gradeDir: string, fileBase: string): string {
  // e.g. grade-3 + math -> grade3Math; grade-3 + grade-3-english -> grade3Grade3English
  const raw = `${gradeDir}_${fileBase}`.replace(/[^a-zA-Z0-9]+/g, "_")
  const parts = raw.split("_").filter(Boolean)
  return parts
    .map((part, i) =>
      i === 0 ? part.toLowerCase() : part.charAt(0).toUpperCase() + part.slice(1).toLowerCase(),
    )
    .join("")
}

function listGradeDirs(): string[] {
  if (!fs.existsSync(CURRICULUM_DIR)) return []
  return fs
    .readdirSync(CURRICULUM_DIR, { withFileTypes: true })
    .filter((d) => d.isDirectory())
    .map((d) => d.name)
    .sort()
}

function main() {
  const imports: string[] = []
  const gradeBlocks: string[] = []
  let importCount = 0

  for (const gradeDir of listGradeDirs()) {
    const gradePath = path.join(CURRICULUM_DIR, gradeDir)
    const metaPath = path.join(gradePath, "meta.json")
    if (!fs.existsSync(metaPath)) {
      console.warn(`[curriculum] skip ${gradeDir}: no meta.json`)
      continue
    }

    const meta = JSON.parse(fs.readFileSync(metaPath, "utf8")) as MetaJson
    const metaIdent = toIdent(gradeDir, "meta")
    imports.push(
      `import ${metaIdent} from "@/data/curriculum/${gradeDir}/meta.json"`,
    )
    importCount++

    const subjectFiles = fs
      .readdirSync(gradePath)
      .filter((f) => f.endsWith(".json") && f !== "meta.json")
      .sort()

    const subjects: { ident: string; id: string; file: string }[] = []
    for (const file of subjectFiles) {
      const filePath = path.join(gradePath, file)
      const data = JSON.parse(fs.readFileSync(filePath, "utf8")) as SubjectJson
      if (!data.id) {
        throw new Error(`[curriculum] ${gradeDir}/${file} is missing "id"`)
      }
      const base = file.replace(/\.json$/, "")
      const ident = toIdent(gradeDir, base)
      imports.push(
        `import ${ident} from "@/data/curriculum/${gradeDir}/${file}"`,
      )
      importCount++
      subjects.push({ ident, id: data.id, file })
    }

    const order = meta.subjectOrder
    if (order?.length) {
      const rank = new Map(order.map((id, i) => [id, i]))
      subjects.sort((a, b) => {
        const ai = rank.has(a.id) ? rank.get(a.id)! : Number.MAX_SAFE_INTEGER
        const bi = rank.has(b.id) ? rank.get(b.id)! : Number.MAX_SAFE_INTEGER
        if (ai !== bi) return ai - bi
        return a.id.localeCompare(b.id)
      })
    } else {
      subjects.sort((a, b) => a.id.localeCompare(b.id))
    }

    const subjectList = subjects.map((s) => s.ident).join(", ")
    gradeBlocks.push(`  {
    ...${metaIdent},
    subjects: [${subjectList}],
  }`)
  }

  const body = `/* eslint-disable */
// AUTO-GENERATED by scripts/generate-curriculum.ts — do not edit by hand.
// Add subject JSON under data/curriculum/<grade>/ then re-run the script.

${imports.join("\n")}

export const gradeData = [
${gradeBlocks.join(",\n")},
] as const
`

  fs.mkdirSync(path.dirname(OUT_FILE), { recursive: true })
  fs.writeFileSync(OUT_FILE, body, "utf8")
  console.log(
    `[curriculum] wrote ${path.relative(ROOT, OUT_FILE)} (${importCount} imports, ${gradeBlocks.length} grades)`,
  )
}

main()
